### ISSUE TITLE
Remove .Rhistory, .Rproj.user

### ISSUE THREAD

**Issue by mpadge** [giovsaraceno/QuadratiK-package#2]
Hi @giovsaraceno, i was just checking out your compliance statements for probability distributions, and noticed you've got the `.Rhistory` file, and `.Rproj.user` directory here. Those contain personal stuff unrelated to the functionality of the repo, and should be removed here. Thanks!

**Comment by giovsaraceno** [comment]
Hi @mpadge, thank you for pointing out the presence of the .Rhistory file and .Rproj.user directory in our repository.
I have now removed those elements. Thanks again!
Giovanni
